[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
clmm_cpi_example = "8wGnAiSXYK31kdas6qNgfr8N3pzHoBEAaDK824qgYE81"

[registry]
url = "https://github.com/raydium-io/raydium-cpi-example"

[provider]
cluster = "Localnet"
wallet = "/home/ubuntu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
